name: Manual Trigger

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting
        run: echo "Hello! This workflow was triggered manually."